spring:
  application:
    name: eunomia
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 9687Luohongwei
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

gitlab:
  host: https://git.tap4fun.com
  defaultNamespace: bi-web
  privateToken: -WawDTNyvtpeHeLeW_b6

redis:
  url: redis://172.20.110.42:6379/11

jenkins:
  host: http://172.20.110.42:8080/
  username: admin
  password: jenkins99
  javajob: eunomia_java
  webjob: eunomia_js
  nodejob: package_common_node

jwt:
  secret: tap4fun.com
  issuer: bi-web

pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

